name: Main workflow
on: 
    workflow_dispatch:
    push:
        branches: 
            - master
        paths-ignore:
            - ".github/workflows/*"
        
env:
    RECORD_KEY: ${{secrets.RECORD_KEY}}

jobs:
    testing1:
        runs-on: ubuntu-latest
        container: 
            image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
        steps:
            - name: Add name vars
              run: export RECORD_KEY=${{env.RECORD_KEY}}
            - name: Get the project code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install --force
            - name: Run tests
              run: npm run cypress:e2e
            - name: Generate reports
              run: npm run report:html
              if: failure() || success()
            - name: Save report
              uses: actions/upload-artifact@v3
              with: 
                path: mochawesome-report
                name: Main report
              if: failure() || success()
            - name: Get report
              uses:  actions/download-artifact@v3
              with:
                name: Main report
              if: failure() || success()

    testing2:
        runs-on: windows-latest
        steps:
            - name: Add name vars
              run: export RECORD_KEY=${{env.RECORD_KEY}}
            - name: Get the project code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install --force
            - name: Run tests
              run: npm run cypress:e2e
            - name: Generate reports
              run: npm run report:html
              if: failure() || success()
            - name: Save report
              uses: actions/upload-artifact@v3
              with: 
                path: mochawesome-report
                name: Main report
              if: failure() || success()
            - name: Get report
              uses:  actions/download-artifact@v3
              with:
                name: Main report
              if: failure() || success()



